# Generated by Django 3.2.13 on 2022-12-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
